import {Clock3,WalletCards} from "lucide-react";
import type {WalletView as WalletViewData} from "@/lib/services/finance-data";
import {PayoutForm} from "@/components/finance/payout-form";

const money=(value:string|undefined,currency="KES")=>`${currency==="KES"?"KSh":currency} ${Number(value??0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function WalletView({data,title}:{data:WalletViewData;title:string}){const s=data.summary;const available=Number(s?.available??0);const minimum=Number(data.minimumPayout);return <>
 <h1 className="text-4xl font-medium tracking-[-.04em] text-plum">{title}</h1>
 <section className="mt-7 overflow-hidden rounded-[2rem] bg-coral p-7 text-white"><WalletCards/><p className="mt-8 text-sm text-white/70">Available to withdraw</p><p className="mt-2 text-5xl font-medium">{money(s?.available,s?.currency)}</p><div className="mt-7 grid grid-cols-2 gap-3"><Metric label="Pending" value={money(s?.pending,s?.currency)}/><Metric label="Total earned" value={money(s?.total_earned,s?.currency)}/></div>{data.pendingPayout?<div className="mt-7 rounded-2xl bg-white/10 p-4"><p className="font-medium">Payout {data.pendingPayout.status.toLowerCase()}</p><p className="mt-1 text-sm text-white/75">{money(data.pendingPayout.amount,data.pendingPayout.currency)} requested {new Date(data.pendingPayout.requested_at).toLocaleDateString()}.</p></div>:<PayoutForm available={available} minimum={minimum} currency={s?.currency??"KES"}/>}<p className="mt-3 text-sm text-white/75">{available<minimum?`You need at least ${money(data.minimumPayout,s?.currency)} before withdrawing.`:"Payout requests are reviewed before transfer."}</p></section>
 <section className="mt-10"><h2 className="text-2xl font-medium text-plum">Recent Activity</h2><div className="mt-4 grid gap-3">{data.activity.map(item=><div key={item.id} className="flex items-center gap-4 rounded-2xl bg-card p-5"><span className="grid size-10 place-items-center rounded-full bg-lavender text-plum"><Clock3 className="size-5"/></span><div className="min-w-0 flex-1"><p className="font-medium">{item.description}</p><p className="text-sm text-muted-foreground">{item.status==="POSTED"&&item.available_at&&new Date(item.available_at)>new Date()?`Pending ${data.settlementHours}-hour review`:item.transaction_type.replaceAll("_"," ")} · {new Date(item.created_at).toLocaleDateString()}</p></div><p className="font-medium text-plum">{item.direction==="CREDIT"?"+":"−"} {money(item.amount,item.currency)}</p></div>)}{!data.activity.length?<p className="rounded-2xl border border-dashed p-7 text-center text-muted-foreground">Your qualified campaign earnings will appear here.</p>:null}</div></section>
 </>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-white/65">{label}</p><p className="mt-1 text-xl font-medium">{value}</p></div>}
