"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { ArrowLeft, ArrowRight, BusFront, Check, Headphones, Megaphone, Radio } from "lucide-react";
import { completeOnboardingAction, type AuthActionState } from "@/app/(auth)/actions";
import { AuthMessage } from "@/components/auth/auth-message";
import { SubmitButton } from "@/components/auth/submit-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { UserRole } from "@/domain/auth/roles";
import { cn } from "@/lib/utils";

type PublicRole=Exclude<UserRole,"ADMIN">;
type ArtistType="INDEPENDENT_ARTIST"|"ARTIST_TEAM"|"LABEL";
type MatatuRelationship="OWNER"|"DRIVER"|"CONDUCTOR"|"CREW_MUSIC_OPERATOR";
const initialState:AuthActionState={status:"idle"};
const roleOptions=[
  { role:"LISTENER" as const,title:"Listener",description:"Discover music, save what you hear and follow what's moving around you.",icon:Headphones,tone:"bg-white" },
  { role:"ARTIST_LABEL" as const,title:"Artist / Label",description:"Promote music and see how campaigns perform.",icon:Megaphone,tone:"bg-lavender" },
  { role:"DJ" as const,title:"DJ",description:"Play new music, build your profile and earn from campaigns.",icon:Radio,tone:"bg-plum text-white" },
  { role:"MATATU_CREW" as const,title:"Matatu Crew",description:"Build your matatu's music identity and earn from campaigns.",icon:BusFront,tone:"bg-coral text-white" },
];
const artistTypes:[ArtistType,string,string][]=[["INDEPENDENT_ARTIST","Independent Artist","It's your music and your name."],["ARTIST_TEAM","Artist Team","A team managing one artist identity."],["LABEL","Label","A home for one or more artists."]];
const relationships:[MatatuRelationship,string][]=[["OWNER","Owner"],["DRIVER","Driver"],["CONDUCTOR","Conductor"],["CREW_MUSIC_OPERATOR","Crew / Music Operator"]];

function Progress({ detail }: { detail:boolean }) { return <div className="mb-8 flex items-center gap-2" aria-label={detail?"Onboarding step 2 of 2":"Onboarding step 1 of 2"}><span className="h-1.5 flex-1 rounded-full bg-coral" /><span className={cn("h-1.5 flex-1 rounded-full",detail?"bg-coral":"bg-border")} /></div>; }
function Field({ name,label,placeholder,required=true,type="text",defaultValue }: { name:string;label:string;placeholder?:string;required?:boolean;type?:string;defaultValue?:string }) { return <div className="grid gap-2"><Label htmlFor={name}>{label}{required?null:<span className="font-normal text-muted-foreground"> (optional)</span>}</Label><Input id={name} name={name} type={type} required={required} defaultValue={defaultValue} placeholder={placeholder} className="h-12 rounded-xl" /></div>; }

export function OnboardingFlow({ displayName }: { displayName:string }) {
  const [role,setRole]=useState<PublicRole|null>(null); const [artistType,setArtistType]=useState<ArtistType|null>(null); const [relationship,setRelationship]=useState<MatatuRelationship|null>(null); const [state,action]=useActionState(completeOnboardingAction,initialState);
  if(state.status==="success"&&role) { const copy=role==="LISTENER"?"Start discovering what Kenya is listening to.":"Your Sauti space is ready for you."; const cta=role==="ARTIST_LABEL"?"Go to Artist Dashboard":role==="DJ"?"Enter Sauti DJ":role==="MATATU_CREW"?"Open My Matatu":"Explore Sauti"; return <div className="mx-auto max-w-xl py-10 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-lime text-plum"><Check className="size-7" /></span><h1 className="mt-7 text-5xl font-medium tracking-[-.05em] text-plum">You&apos;re in.</h1><p className="mt-4 text-lg text-muted-foreground">{copy}</p><Button asChild className="mt-9 h-13 rounded-full px-8 text-base"><Link href={state.destination??"/"}>{cta}<ArrowRight /></Link></Button></div>; }
  if(!role) return <div><Progress detail={false} /><p className="text-sm font-medium text-coral">Step 2 of 2</p><h1 className="mt-2 text-4xl font-medium tracking-[-.04em] text-plum sm:text-5xl">What brings you to Sauti?</h1><p className="mt-3 text-muted-foreground">Choose your main Sauti experience for now.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{roleOptions.map(({role:value,title,description,icon:Icon,tone})=><button key={value} type="button" onClick={()=>setRole(value)} className={cn("group min-h-52 rounded-3xl p-6 text-left transition-all hover:-translate-y-1 hover:shadow-lg focus-visible:ring-2 focus-visible:ring-ring",tone)}><Icon className="size-6" /><h2 className="mt-12 text-xl font-medium">{title}</h2><p className="mt-2 text-sm leading-6 opacity-65">{description}</p></button>)}</div></div>;
  if(role==="ARTIST_LABEL"&&!artistType) return <div><Progress detail /><button type="button" onClick={()=>setRole(null)} className="mb-6 flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Back</button><p className="text-sm font-medium text-coral">Artist setup</p><h1 className="mt-2 text-4xl font-medium tracking-[-.04em] text-plum">Who are you joining as?</h1><div className="mt-8 grid gap-3">{artistTypes.map(([value,title,description])=><button key={value} type="button" onClick={()=>setArtistType(value)} className="flex items-center justify-between rounded-2xl border bg-white p-5 text-left transition-colors hover:border-coral"><div><h2 className="font-medium text-plum">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><ArrowRight className="size-5 text-coral" /></button>)}</div></div>;
  return <div><Progress detail /><button type="button" onClick={()=>{ if(role==="ARTIST_LABEL") setArtistType(null); else setRole(null); }} className="mb-6 flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Back</button><p className="text-sm font-medium text-coral">{role==="LISTENER"?"Listener setup":role==="ARTIST_LABEL"?"Artist setup":role==="DJ"?"DJ setup":"Matatu setup"}</p><h1 className="mt-2 text-4xl font-medium tracking-[-.04em] text-plum">{role==="LISTENER"?"Make Sauti yours.":role==="ARTIST_LABEL"?"Tell us about your music home.":role==="DJ"?"Build your DJ identity.":"Tell us about your matatu."}</h1>
    <form action={action} className="mt-8 grid gap-5"><input type="hidden" name="role" value={role} />{artistType?<input type="hidden" name="account_type" value={artistType} />:null}{relationship?<input type="hidden" name="relationship" value={relationship} />:null}
      {role==="LISTENER"?<><Field name="display_name" label="Display name" defaultValue={displayName} required={false} /><div className="grid gap-4 sm:grid-cols-2"><Field name="county" label="County" placeholder="Nairobi" required={false} /><Field name="town_area" label="Town / area" placeholder="Kilimani" required={false} /></div><Field name="genres" label="Favourite genres" placeholder="Afropop, Gengetone, Amapiano" required={false} /></>:null}
      {role==="ARTIST_LABEL"?<><Field name="name" label="Artist / label name" defaultValue={artistType==="INDEPENDENT_ARTIST"?displayName:""} /><Field name="handle" label="Public handle" placeholder="nairobisound" /><div className="grid gap-4 sm:grid-cols-2"><Field name="county" label="County" placeholder="Nairobi" /><Field name="town_area" label="Town / area" placeholder="Westlands" required={false} /></div><Field name="avatar_url" label="Profile image URL" placeholder="https://…" required={false} type="url" /><div className="grid gap-2"><Label htmlFor="bio">Short bio <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="bio" name="bio" maxLength={1000} className="min-h-24 rounded-xl" /></div><p className="rounded-2xl bg-lavender p-4 text-sm leading-6 text-plum">When you upload music for a Sauti campaign, you&apos;ll need to confirm that you own the music or have permission to promote it.</p></>:null}
      {role==="DJ"?<><Field name="stage_name" label="Stage name" defaultValue={displayName} /><Field name="handle" label="Public handle" placeholder="djkev" /><div className="grid gap-4 sm:grid-cols-2"><Field name="county" label="County" placeholder="Nairobi" /><Field name="town_area" label="Town / area" placeholder="Kasarani" /></div><Field name="genres" label="Main genres" placeholder="Afropop, Gengetone, Amapiano" /><Field name="avatar_url" label="Profile image URL" placeholder="https://…" required={false} type="url" /><div className="grid gap-2"><Label htmlFor="bio">Short bio <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="bio" name="bio" maxLength={500} className="min-h-24 rounded-xl" /></div><div className="rounded-2xl bg-plum p-5 text-white"><p className="font-medium">With Sauti DJ you can:</p><ul className="mt-3 grid gap-2 text-sm text-white/65"><li>• find music campaigns</li><li>• build your set history later</li><li>• grow your DJ profile</li><li>• earn from qualified campaigns</li></ul></div></>:null}
      {role==="MATATU_CREW"?<><Field name="name" label="Matatu display name" placeholder="Niaje 254" /><Field name="sacco_name" label="SACCO name" placeholder="Umoja One Sacco" /><Field name="main_route" label="Main route" placeholder="CBD – Umoja" /><div className="grid gap-4 sm:grid-cols-2"><Field name="county" label="County" placeholder="Nairobi" /><Field name="town_area" label="Town / area" placeholder="Umoja" /></div><Field name="avatar_url" label="Profile image URL" placeholder="https://…" required={false} type="url" /><fieldset><legend className="text-sm font-medium">Your relationship</legend><div className="mt-3 grid grid-cols-2 gap-2">{relationships.map(([value,label])=><button key={value} type="button" onClick={()=>setRelationship(value)} className={cn("min-h-12 rounded-xl border px-3 text-sm font-medium transition-colors",relationship===value?"border-coral bg-coral/8 text-coral":"bg-white hover:border-coral")}>{label}</button>)}</div>{!relationship?<p className="mt-2 text-xs text-muted-foreground">Choose one relationship to continue.</p>:null}</fieldset></>:null}
      <AuthMessage status={state.status} message={state.message} />
      <SubmitButton>{role==="LISTENER"?"Explore Sauti":role==="ARTIST_LABEL"?"Go to Artist Dashboard":role==="DJ"?"Enter Sauti DJ":"Open My Matatu"}</SubmitButton>{role==="LISTENER"?<button type="submit" formNoValidate className="text-sm font-medium text-muted-foreground hover:text-plum">Skip preferences</button>:null}
    </form>
  </div>;
}
