begin;
create or replace function public.register_mpesa_payout(p_payout_id uuid,p_originator_id text,p_conversation_id text)returns void language plpgsql security definer set search_path='' as $$declare p public.payout_requests;available numeric;begin if not public.is_admin()then raise exception'ADMIN_REQUIRED';end if;select*into p from public.payout_requests where id=p_payout_id for update;if p.id is null or p.status<>'REQUESTED'or p.method<>'MPESA_B2C'then raise exception'PAYOUT_NOT_ACTIONABLE';end if;select s.available into available from public.wallet_financial_summary s where s.wallet_id=p.wallet_id;if available<p.amount then raise exception'INSUFFICIENT_AVAILABLE_BALANCE';end if;update public.payout_requests set status='PROCESSING',metadata=metadata||jsonb_build_object('provider','MPESA_B2C','originator_conversation_id',p_originator_id,'conversation_id',p_conversation_id,'dispatched_at',now())where id=p.id;end$$;
revoke execute on function public.register_mpesa_payout(uuid,text,text)from public,anon;grant execute on function public.register_mpesa_payout(uuid,text,text)to authenticated;
create or replace function public.record_mpesa_payout_dispatch(p_payout_id uuid,p_conversation_id text)returns void language plpgsql security definer set search_path='' as $$begin if not public.is_admin()then raise exception'ADMIN_REQUIRED';end if;update public.payout_requests set metadata=metadata||jsonb_build_object('conversation_id',p_conversation_id)where id=p_payout_id and status='PROCESSING';end$$;
create or replace function public.fail_mpesa_payout_dispatch(p_payout_id uuid,p_reason text)returns void language plpgsql security definer set search_path='' as $$begin if not public.is_admin()then raise exception'ADMIN_REQUIRED';end if;update public.payout_requests set status='FAILED',processed_at=now(),failure_reason=left(p_reason,500),metadata=metadata||jsonb_build_object('dispatch_failed',true)where id=p_payout_id and status='PROCESSING';end$$;
revoke execute on function public.record_mpesa_payout_dispatch(uuid,text),public.fail_mpesa_payout_dispatch(uuid,text)from public,anon;grant execute on function public.record_mpesa_payout_dispatch(uuid,text),public.fail_mpesa_payout_dispatch(uuid,text)to authenticated;
create or replace function public.complete_mpesa_payout(p_originator_id text,p_result_code integer,p_result_description text,p_receipt text,p_conversation_id text,p_proof text)returns jsonb language plpgsql security definer set search_path='' as $$declare p public.payout_requests;secret text;expected text;begin select callback_secret into secret from public.mpesa_private_config where id=true;expected:=encode(extensions.hmac('b2c:'||p_originator_id||':'||p_result_code||':'||coalesce(p_receipt,''),secret,'sha256'),'hex');if expected is null or expected<>p_proof then raise exception'INVALID_PROOF';end if;select*into p from public.payout_requests where metadata->>'originator_conversation_id'=p_originator_id for update;if p.id is null then raise exception'PAYOUT_NOT_FOUND';end if;if p.status<>'PROCESSING'then return jsonb_build_object('duplicate',true);end if;if p_result_code=0 then if coalesce(p_receipt,'')=''then raise exception'MISSING_RECEIPT';end if;insert into public.ledger_transactions(wallet_id,transaction_type,direction,amount,currency,reference_type,reference_id,description,status,idempotency_key,posted_at,created_by,metadata)values(p.wallet_id,'PAYOUT','DEBIT',p.amount,p.currency,'payout_request',p.id,'M-Pesa payout completed','POSTED','mpesa-b2c:'||p.id,now(),p.requested_by,jsonb_build_object('receipt',p_receipt,'conversation_id',p_conversation_id));update public.payout_requests set status='COMPLETED',processed_at=now(),external_transaction_id=p_receipt,metadata=metadata||jsonb_build_object('result_code',p_result_code,'result_description',left(p_result_description,500))where id=p.id;else update public.payout_requests set status='FAILED',processed_at=now(),failure_reason=left(p_result_description,500),metadata=metadata||jsonb_build_object('result_code',p_result_code,'conversation_id',p_conversation_id)where id=p.id;end if;insert into public.notifications(recipient_profile_id,notification_type,title,body,metadata,link_url)values(p.requested_by,'PAYOUT_UPDATE',case when p_result_code=0 then'Payout completed'else'Payout failed'end,case when p_result_code=0 then'Your M-Pesa payout has been sent.'else'Your payout was not completed. Your balance remains available.'end,jsonb_build_object('payout_id',p.id,'status',case when p_result_code=0 then'COMPLETED'else'FAILED'end),'/notifications');return jsonb_build_object('status',case when p_result_code=0 then'COMPLETED'else'FAILED'end);end$$;
revoke execute on function public.complete_mpesa_payout(text,integer,text,text,text,text)from public,authenticated;grant execute on function public.complete_mpesa_payout(text,integer,text,text,text,text)to anon;
commit;
