insert into public.business_settings(key,value) values ('runtime_policy','{"finance_simulation":false,"mock_payouts":false,"demo_data":false}'::jsonb) on conflict(key) do nothing;
create index if not exists idx_profiles_role_status on public.profiles(role,account_status);
create index if not exists idx_campaigns_status_dates on public.campaigns(status,start_date,end_date);
create index if not exists idx_play_event_flags_open_created on public.play_event_flags(resolved_at,created_at desc) where resolved_at is null;
create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);
create index if not exists idx_notifications_recipient_unread on public.notifications(recipient_profile_id,created_at desc) where read_at is null;
create index if not exists idx_song_requests_rate_lookup on public.song_requests(requester_profile_id,created_at desc);
create or replace function public.create_song_request(p_target_type public.song_request_target_type,p_target_id uuid,p_song_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare profile_id uuid;request_id uuid;begin profile_id:=public.current_profile_id();if profile_id is null then raise exception 'AUTH_REQUIRED';end if;if(select role from public.profiles where id=profile_id)<>'LISTENER' then raise exception 'ROLE_REQUIRED';end if;if(select count(*) from public.song_requests where requester_profile_id=profile_id and created_at>now()-interval '1 minute')>=5 then raise exception 'RATE_LIMITED';end if;if p_target_type='DJ' and not exists(select 1 from public.dj_profiles where id=p_target_id and status='ACTIVE')then raise exception 'TARGET_UNAVAILABLE';end if;if p_target_type='MATATU' and not exists(select 1 from public.matatus where id=p_target_id and status='ACTIVE')then raise exception 'TARGET_UNAVAILABLE';end if;if not exists(select 1 from public.songs where id=p_song_id and status in('APPROVED','PUBLISHED'))then raise exception 'SONG_UNAVAILABLE';end if;insert into public.song_requests(requester_profile_id,target_type,target_id,song_id,status)values(profile_id,p_target_type,p_target_id,p_song_id,'PENDING')returning id into request_id;return request_id;end$$;
revoke execute on function public.create_song_request(public.song_request_target_type,uuid,uuid) from public,anon;grant execute on function public.create_song_request(public.song_request_target_type,uuid,uuid) to authenticated;
