begin;
create type public.campaign_funding_status as enum('NOT_FUNDED','PENDING','FUNDED','PARTIALLY_REFUNDED','REFUNDED');
create type public.campaign_draft_state as enum('DRAFT','SUBMITTED','CANCELLED');
alter table public.campaigns add column funding_status public.campaign_funding_status not null default 'NOT_FUNDED',add column submitted_at timestamptz,add column configuration_snapshot jsonb not null default '{}'::jsonb;
create table public.business_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());
insert into public.business_settings values('campaign_pricing','{"minimum_budget":5000,"platform_commission_rate":0.20,"payout_fee_rate":0,"tax_rate":0,"currency":"KES"}');
create table public.campaign_drafts(id uuid primary key default gen_random_uuid(),artist_account_id uuid not null references public.artist_accounts(id) on delete cascade,owner_profile_id uuid not null references public.profiles(id) on delete cascade,song_id uuid references public.songs(id) on delete restrict,current_step smallint not null default 1 check(current_step between 1 and 8),configuration jsonb not null default '{}'::jsonb check(jsonb_typeof(configuration)='object'),state public.campaign_draft_state not null default 'DRAFT',submitted_campaign_id uuid references public.campaigns(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger campaign_drafts_updated_at before update on public.campaign_drafts for each row execute function public.set_updated_at();
alter table public.business_settings enable row level security;alter table public.campaign_drafts enable row level security;
create policy settings_read on public.business_settings for select to authenticated using(true);create policy drafts_owner_all on public.campaign_drafts for all to authenticated using(owner_profile_id=public.current_profile_id() and public.can_manage_artist(artist_account_id)) with check(owner_profile_id=public.current_profile_id() and public.can_manage_artist(artist_account_id));
grant select on public.business_settings to authenticated;grant select,insert,update,delete on public.campaign_drafts to authenticated;
create function public.submit_campaign_draft(p_draft_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare d public.campaign_drafts;cfg jsonb;budget numeric;starts date;ends date;types text[];minimum numeric;campaign_id uuid;
begin select * into d from public.campaign_drafts where id=p_draft_id and owner_profile_id=public.current_profile_id() and state='DRAFT' for update;if d.id is null then raise exception 'DRAFT_NOT_FOUND';end if;cfg=d.configuration;budget=(cfg->>'budget')::numeric;starts=(cfg->>'start_date')::date;ends=(cfg->>'end_date')::date;types=array(select jsonb_array_elements_text(coalesce(cfg->'participant_types','[]')));select (value->>'minimum_budget')::numeric into minimum from public.business_settings where key='campaign_pricing';if d.song_id is null or not exists(select 1 from public.songs s where s.id=d.song_id and s.artist_account_id=d.artist_account_id and s.audio_asset_url is not null and s.rights_declaration_accepted) then raise exception 'SONG_NOT_ELIGIBLE';end if;if cardinality(types)=0 or exists(select 1 from unnest(types)t where t not in('DJ','MATATU')) then raise exception 'PARTICIPANTS_REQUIRED';end if;if starts<current_date or ends<starts then raise exception 'INVALID_DATES';end if;if budget<minimum then raise exception 'MINIMUM_BUDGET';end if;
insert into public.campaigns(artist_account_id,song_id,campaign_name,objective,total_budget,currency,start_date,end_date,status,approval_status,funding_status,submitted_at,configuration_snapshot) values(d.artist_account_id,d.song_id,coalesce(nullif(cfg->>'campaign_name',''),'Promote '||(select title from public.songs where id=d.song_id)),'DISCOVERY',budget,'KES',starts,ends,'PENDING_APPROVAL','PENDING','NOT_FUNDED',now(),cfg) returning id into campaign_id;insert into public.campaign_participant_types(campaign_id,participant_type) select campaign_id,t::public.participant_type from unnest(types)t;insert into public.campaign_targets(campaign_id,target_type,text_value,dj_profile_id,matatu_id) select campaign_id,(x->>'target_type')::public.target_type,nullif(x->>'text_value',''),case when x->>'target_type'='DJ' then nullif(x->>'entity_id','')::uuid end,case when x->>'target_type'='MATATU' then nullif(x->>'entity_id','')::uuid end from jsonb_array_elements(coalesce(cfg->'targets','[]'))x;update public.campaign_drafts set state='SUBMITTED',submitted_campaign_id=campaign_id,current_step=8 where id=d.id;insert into public.notifications(recipient_profile_id,notification_type,title,body,metadata,link_url) select id,'CAMPAIGN_AVAILABLE','Campaign awaiting review',(select campaign_name from public.campaigns where id=campaign_id),jsonb_build_object('campaign_id',campaign_id),'/admin' from public.profiles where role='ADMIN' and account_status='ACTIVE';return campaign_id;end $$;
grant execute on function public.submit_campaign_draft(uuid) to authenticated;
commit;
