begin;
drop function if exists public.start_matatu_playback(uuid);
drop function if exists public.finish_matatu_playback(uuid,integer);
revoke all on function public.refresh_account_risk(uuid) from public,anon,authenticated;

create or replace function public.admin_review_play(p_play_id uuid,p_outcome public.admin_review_outcome,p_reason text,p_note text) returns void language plpgsql security definer set search_path='' as $$
declare actor uuid;pe public.play_events;part public.campaign_participations;participant_profile uuid;campaign_wallet uuid;earning_wallet uuid;reward numeric;transfer uuid:=gen_random_uuid();prior public.verification_decisions;next_version integer;
begin
 if not public.is_admin() then raise exception 'Admin access required';end if;if p_outcome not in('APPROVED','REJECTED','KEPT_FLAGGED') or length(trim(p_reason))<3 then raise exception 'Invalid review';end if;
 actor=public.current_profile_id();select * into pe from public.play_events where id=p_play_id for update;if pe.id is null then raise exception 'Play not found';end if;
 select * into prior from public.verification_decisions where play_event_id=pe.id order by decision_version desc limit 1;next_version=coalesce(prior.decision_version,0)+1;
 insert into public.admin_review_decisions(entity_type,entity_id,outcome,public_message,internal_note,actor_profile_id,previous_state,new_state) values('play_event',pe.id,p_outcome,p_reason,p_note,actor,jsonb_build_object('verification_status',pe.verification_status,'qualification_status',pe.qualification_status),jsonb_build_object('admin_outcome',p_outcome));
 update public.play_events set original_qualification_status=coalesce(original_qualification_status,qualification_status),admin_review_status=p_outcome,admin_reviewed_by=actor,admin_reviewed_at=now(),verification_status=case when p_outcome='APPROVED' then 'VERIFIED' when p_outcome='REJECTED' then 'REJECTED' else 'FLAGGED' end,qualification_status=case when p_outcome='APPROVED' then 'QUALIFIED' when p_outcome='REJECTED' then 'NOT_QUALIFIED' else 'REVIEW_REQUIRED' end,qualified_at=case when p_outcome='APPROVED' then coalesce(qualified_at,now()) else null end where id=pe.id;
 insert into public.verification_decisions(play_event_id,decision_version,source,verification_status,qualification_status,risk_level,reason_codes,reward_eligible,reward_amount,rule_snapshot,evidence_summary,actor_profile_id,reprocess_reason,supersedes_decision_id)
 values(pe.id,next_version,'ADMIN',case when p_outcome='APPROVED' then 'VERIFIED'::public.verification_status when p_outcome='REJECTED' then 'REJECTED'::public.verification_status else 'FLAGGED'::public.verification_status end,case when p_outcome='APPROVED' then 'QUALIFIED'::public.qualification_status when p_outcome='REJECTED' then 'NOT_QUALIFIED'::public.qualification_status else 'REVIEW_REQUIRED'::public.qualification_status end,case when p_outcome='KEPT_FLAGGED' then 'HIGH'::public.risk_level else pe.risk_level end,array['ADMIN_'||p_outcome],p_outcome='APPROVED',coalesce(pe.reward_amount,prior.reward_amount),coalesce(nullif(pe.rule_snapshot,'{}'::jsonb),prior.rule_snapshot,'{}'::jsonb),jsonb_build_object('reason',p_reason),actor,p_reason,prior.id);
 if p_outcome='APPROVED' then
  select * into part from public.campaign_participations where id=pe.campaign_participation_id;reward=coalesce(pe.reward_amount,(pe.rule_snapshot->>'participant_reward_kes')::numeric,40);
  if part.participant_type='DJ' then select profile_id into participant_profile from public.dj_profiles where id=part.dj_profile_id;else select profile_id into participant_profile from public.matatu_crew_memberships where matatu_id=part.matatu_id order by case membership_role when 'OWNER' then 0 else 1 end limit 1;end if;
  select id into campaign_wallet from public.wallets where campaign_id=pe.campaign_id and wallet_type='CAMPAIGN_BUDGET' for update;insert into public.wallets(owner_type,profile_id,wallet_type,currency) values('PROFILE',participant_profile,'EARNINGS','KES') on conflict do nothing;select id into earning_wallet from public.wallets where profile_id=participant_profile and wallet_type='EARNINGS' and currency='KES';
  insert into public.ledger_transactions(wallet_id,transaction_type,direction,amount,currency,reference_type,reference_id,description,status,idempotency_key,transfer_id,created_by,metadata) values(campaign_wallet,'CAMPAIGN_HOLD','DEBIT',reward,'KES','play_event',pe.id,'Admin-approved play pending settlement','PENDING','admin-review-hold-debit:'||pe.id,transfer,actor,jsonb_build_object('review_version',next_version)),(earning_wallet,'PARTICIPANT_EARNING','CREDIT',reward,'KES','play_event',pe.id,'Admin-approved earning pending settlement','PENDING','admin-review-hold-credit:'||pe.id,transfer,actor,jsonb_build_object('review_version',next_version)) on conflict(idempotency_key) do nothing;
  update public.play_events set reward_amount=reward,reward_status='PENDING' where id=pe.id;
 end if;
 if p_outcome='REJECTED' then update public.ledger_transactions set status='CANCELLED' where reference_type='play_event' and reference_id=pe.id and status='PENDING';update public.play_events set reward_status='CANCELLED' where id=pe.id and reward_status='PENDING';end if;
 update public.play_event_flags set status=case when p_outcome='KEPT_FLAGGED' then 'OPEN'::public.review_status else 'CONFIRMED'::public.review_status end,reviewed_by=actor,reviewed_at=now(),resolved_at=case when p_outcome='KEPT_FLAGGED' then null else now() end,resolution=p_reason,admin_notes=p_note where play_event_id=pe.id;
 insert into public.audit_logs(actor_profile_id,action,entity_type,entity_id,previous_data,new_data,metadata) values(actor,'PLAY_'||p_outcome,'play_event',pe.id,jsonb_build_object('verification_status',pe.verification_status,'qualification_status',pe.qualification_status),jsonb_build_object('admin_outcome',p_outcome,'decision_version',next_version),jsonb_build_object('reason',p_reason,'note',p_note));
end$$;
grant execute on function public.admin_review_play(uuid,public.admin_review_outcome,text,text) to authenticated;
commit;
