begin;

alter type public.account_status rename value 'DEACTIVATED' to 'CLOSED';
alter type public.account_status add value if not exists 'UNDER_REVIEW';
commit;
begin;

create type public.admin_review_outcome as enum ('APPROVED','REJECTED','CHANGES_REQUESTED','PAUSED','CANCELLED','KEPT_FLAGGED');
create type public.dispute_type as enum ('REJECTED_PLAY','MISSING_EARNING','CAMPAIGN','PAYOUT','OTHER');
create type public.dispute_status as enum ('OPEN','IN_REVIEW','RESOLVED','REJECTED');

alter table public.campaigns add column rejection_category text,add column rejected_by uuid references public.profiles(id),add column rejected_at timestamptz,add column internal_review_note text,add column changes_requested text;
alter table public.play_events add column original_qualification_status public.qualification_status,add column admin_review_status public.admin_review_outcome,add column admin_reviewed_by uuid references public.profiles(id),add column admin_reviewed_at timestamptz;

create table public.admin_review_decisions(id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid not null,outcome public.admin_review_outcome not null,reason_category text,public_message text,internal_note text,actor_profile_id uuid not null references public.profiles(id),previous_state jsonb,new_state jsonb,created_at timestamptz not null default now());
create table public.admin_notes(id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid not null,note text not null check(length(trim(note))>=3),author_profile_id uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.disputes(id uuid primary key default gen_random_uuid(),dispute_type public.dispute_type not null,opened_by uuid references public.profiles(id),related_entity_type text not null,related_entity_id uuid,status public.dispute_status not null default 'OPEN',description text not null,admin_notes text,resolution text,created_at timestamptz not null default now(),resolved_at timestamptz,updated_at timestamptz not null default now());
create table public.business_setting_versions(id bigint generated always as identity primary key,setting_key text not null,value jsonb not null,effective_at timestamptz not null default now(),changed_by uuid not null references public.profiles(id),reason text not null,created_at timestamptz not null default now());
create index admin_review_entity_idx on public.admin_review_decisions(entity_type,entity_id,created_at desc);create index admin_notes_entity_idx on public.admin_notes(entity_type,entity_id,created_at desc);create index disputes_status_idx on public.disputes(status,created_at desc);create index settings_version_key_idx on public.business_setting_versions(setting_key,effective_at desc);
create trigger review_decisions_immutable before update or delete on public.admin_review_decisions for each row execute function public.prevent_mutation();create trigger admin_notes_immutable before update or delete on public.admin_notes for each row execute function public.prevent_mutation();create trigger settings_versions_immutable before update or delete on public.business_setting_versions for each row execute function public.prevent_mutation();create trigger disputes_updated_at before update on public.disputes for each row execute function public.set_updated_at();

insert into public.business_settings(key,value) values('operations_policy','{"participant_reward_kes":40,"minimum_playback_percentage":80,"cooldown_minutes":30,"daily_play_limit":20,"maintenance_mode":false,"campaign_review_required":true,"supported_currency":"KES"}') on conflict(key) do nothing;

create function public.require_active_marketplace_actor() returns trigger language plpgsql security definer set search_path='' as $$declare pid uuid;state public.account_status;begin select public.current_profile_id() into pid;if pid is null then return new;end if;select account_status into state from public.profiles where id=pid;if state<>'ACTIVE' then raise exception 'Account is not active';end if;return new;end$$;
create trigger campaign_drafts_active_actor before insert or update on public.campaign_drafts for each row execute function public.require_active_marketplace_actor();
create trigger participations_active_actor before insert or update on public.campaign_participations for each row execute function public.require_active_marketplace_actor();
create trigger dj_sets_active_actor before insert or update on public.dj_sets for each row execute function public.require_active_marketplace_actor();
create trigger playback_active_actor before insert or update on public.playback_sessions for each row execute function public.require_active_marketplace_actor();

create function public.activate_approved_funded_campaign() returns trigger language plpgsql security definer set search_path='' as $$begin if new.approval_status='APPROVED' and new.funding_status in('FUNDED','PARTIALLY_SPENT') and new.status='PENDING_APPROVAL' then new.status='ACTIVE';end if;return new;end$$;
create trigger campaign_activate_when_ready before update of funding_status,approval_status on public.campaigns for each row execute function public.activate_approved_funded_campaign();

create function public.admin_review_campaign(p_campaign_id uuid,p_outcome public.admin_review_outcome,p_category text,p_public_message text,p_internal_note text) returns void language plpgsql security definer set search_path='' as $$declare actor uuid;c public.campaigns;artist_profile uuid;next_status public.campaign_status;next_approval public.campaign_approval_status;title text;
begin if not public.is_admin() then raise exception 'Admin access required';end if;select public.current_profile_id() into actor;select * into c from public.campaigns where id=p_campaign_id for update;if c.id is null then raise exception 'Campaign not found';end if;
 if p_outcome='APPROVED' then next_approval='APPROVED';next_status=case when c.funding_status in('FUNDED','PARTIALLY_SPENT') then 'ACTIVE' else 'PENDING_APPROVAL' end;title='Campaign approved';
 elsif p_outcome='REJECTED' then if length(trim(coalesce(p_category,'')))<3 or length(trim(coalesce(p_public_message,'')))<3 then raise exception 'Rejection category and message required';end if;next_approval='REJECTED';next_status='REJECTED';title='Campaign not approved';
 elsif p_outcome='CHANGES_REQUESTED' then next_approval='NOT_SUBMITTED';next_status='DRAFT';title='Changes requested';
 elsif p_outcome='PAUSED' then next_approval=c.approval_status;next_status='PAUSED';title='Campaign paused';
 elsif p_outcome='CANCELLED' then next_approval=c.approval_status;next_status='CANCELLED';title='Campaign cancelled';else raise exception 'Unsupported campaign outcome';end if;
 update public.campaigns set approval_status=next_approval,status=next_status,approved_by=case when p_outcome='APPROVED' then actor else approved_by end,approved_at=case when p_outcome='APPROVED' then now() else approved_at end,rejection_category=case when p_outcome='REJECTED' then p_category end,rejected_by=case when p_outcome='REJECTED' then actor end,rejected_at=case when p_outcome='REJECTED' then now() end,approval_notes=p_public_message,internal_review_note=p_internal_note,changes_requested=case when p_outcome='CHANGES_REQUESTED' then p_public_message end,paused_at=case when p_outcome='PAUSED' then now() else paused_at end where id=c.id;
 insert into public.admin_review_decisions(entity_type,entity_id,outcome,reason_category,public_message,internal_note,actor_profile_id,previous_state,new_state) values('campaign',c.id,p_outcome,p_category,p_public_message,p_internal_note,actor,jsonb_build_object('status',c.status,'approval_status',c.approval_status),jsonb_build_object('status',next_status,'approval_status',next_approval));
 insert into public.audit_logs(actor_profile_id,action,entity_type,entity_id,previous_data,new_data,metadata) values(actor,'CAMPAIGN_'||p_outcome,'campaign',c.id,jsonb_build_object('status',c.status,'approval_status',c.approval_status),jsonb_build_object('status',next_status,'approval_status',next_approval),jsonb_build_object('category',p_category,'internal_note',p_internal_note));
 select m.profile_id into artist_profile from public.artist_account_memberships m where m.artist_account_id=c.artist_account_id and m.membership_role in('OWNER','ADMIN') limit 1;insert into public.notifications(recipient_profile_id,notification_type,title,body,metadata,link_url) values(artist_profile,case when p_outcome='APPROVED' then 'CAMPAIGN_APPROVED'::public.notification_type else 'CAMPAIGN_REJECTED'::public.notification_type end,title,coalesce(nullif(p_public_message,''),'Your campaign review status changed.'),jsonb_build_object('campaign_id',c.id,'outcome',p_outcome),'/artist/campaigns/'||c.id);end$$;

create function public.admin_set_account_status(p_profile_id uuid,p_status public.account_status,p_reason text,p_note text) returns void language plpgsql security definer set search_path='' as $$declare actor uuid;old public.profiles;begin if not public.is_admin() then raise exception 'Admin access required';end if;if p_status not in('ACTIVE','SUSPENDED','UNDER_REVIEW') or length(trim(p_reason))<3 then raise exception 'Invalid status or missing reason';end if;select public.current_profile_id() into actor;select * into old from public.profiles where id=p_profile_id for update;if old.role='ADMIN' then raise exception 'Admin accounts require owner-level management';end if;update public.profiles set account_status=p_status where id=p_profile_id;update public.dj_profiles set status=case when p_status='ACTIVE' then 'ACTIVE'::public.account_status else 'SUSPENDED'::public.account_status end where profile_id=p_profile_id;update public.matatus set status=case when p_status='ACTIVE' then 'ACTIVE'::public.account_status else 'SUSPENDED'::public.account_status end where id in(select matatu_id from public.matatu_crew_memberships where profile_id=p_profile_id);insert into public.audit_logs(actor_profile_id,action,entity_type,entity_id,previous_data,new_data,metadata) values(actor,'ACCOUNT_'||p_status,'profile',p_profile_id,jsonb_build_object('status',old.account_status),jsonb_build_object('status',p_status),jsonb_build_object('reason',p_reason,'internal_note',p_note));insert into public.notifications(recipient_profile_id,notification_type,title,body,metadata) values(p_profile_id,'PAYOUT_UPDATE',case when p_status='ACTIVE' then 'Account restored' else 'Account status updated' end,p_reason,jsonb_build_object('account_status',p_status));end$$;

create function public.admin_set_verification(p_entity_type text,p_entity_id uuid,p_status public.verification_status,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare actor uuid;begin if not public.is_admin() then raise exception 'Admin access required';end if;if p_status not in('PENDING','VERIFIED','REJECTED') then raise exception 'Unsupported verification state';end if;select public.current_profile_id() into actor;if p_entity_type='DJ' then update public.dj_profiles set verification_status=p_status where id=p_entity_id;elsif p_entity_type='MATATU' then update public.matatus set verification_status=p_status where id=p_entity_id;elsif p_entity_type='ARTIST' then update public.artist_accounts set verification_status=p_status where id=p_entity_id;else raise exception 'Unsupported entity type';end if;if not found then raise exception 'Entity not found';end if;insert into public.audit_logs(actor_profile_id,action,entity_type,entity_id,new_data,metadata) values(actor,'VERIFICATION_'||p_status,lower(p_entity_type),p_entity_id,jsonb_build_object('verification_status',p_status),jsonb_build_object('reason',p_reason));end$$;

create function public.admin_review_play(p_play_id uuid,p_outcome public.admin_review_outcome,p_reason text,p_note text) returns void language plpgsql security definer set search_path='' as $$declare actor uuid;pe public.play_events;part public.campaign_participations;participant_profile uuid;campaign_wallet uuid;earning_wallet uuid;reward numeric;transfer uuid:=gen_random_uuid();begin if not public.is_admin() then raise exception 'Admin access required';end if;if p_outcome not in('APPROVED','REJECTED','KEPT_FLAGGED') or length(trim(p_reason))<3 then raise exception 'Invalid review';end if;select public.current_profile_id() into actor;select * into pe from public.play_events where id=p_play_id for update;if pe.id is null then raise exception 'Play not found';end if;insert into public.admin_review_decisions(entity_type,entity_id,outcome,public_message,internal_note,actor_profile_id,previous_state,new_state) values('play_event',pe.id,p_outcome,p_reason,p_note,actor,jsonb_build_object('qualification_status',pe.qualification_status),jsonb_build_object('admin_outcome',p_outcome));
 update public.play_events set original_qualification_status=coalesce(original_qualification_status,qualification_status),admin_review_status=p_outcome,admin_reviewed_by=actor,admin_reviewed_at=now(),qualification_status=case when p_outcome='APPROVED' then 'QUALIFIED'::public.qualification_status when p_outcome='REJECTED' then 'DISQUALIFIED'::public.qualification_status else qualification_status end,qualified_at=case when p_outcome='APPROVED' then coalesce(qualified_at,now()) else qualified_at end where id=pe.id;
 if p_outcome='APPROVED' then select * into part from public.campaign_participations where id=pe.campaign_participation_id;select coalesce((value->>'participant_reward_kes')::numeric,40) into reward from public.business_settings where key='operations_policy';if part.participant_type='DJ' then select profile_id into participant_profile from public.dj_profiles where id=part.dj_profile_id;else select profile_id into participant_profile from public.matatu_crew_memberships where matatu_id=part.matatu_id order by case membership_role when 'OWNER' then 0 else 1 end limit 1;end if;select id into campaign_wallet from public.wallets where campaign_id=pe.campaign_id and wallet_type='CAMPAIGN_BUDGET';insert into public.wallets(owner_type,profile_id,wallet_type,currency) values('PROFILE',participant_profile,'EARNINGS','KES') on conflict do nothing;select id into earning_wallet from public.wallets where profile_id=participant_profile and wallet_type='EARNINGS' and currency='KES';insert into public.ledger_transactions(wallet_id,transaction_type,direction,amount,currency,reference_type,reference_id,description,status,idempotency_key,posted_at,transfer_id,created_by) values(campaign_wallet,'PARTICIPANT_EARNING','DEBIT',reward,'KES','play_event',pe.id,'Admin-qualified campaign play','POSTED','admin-play-debit:'||pe.id,now(),transfer,actor),(earning_wallet,'PARTICIPANT_EARNING','CREDIT',reward,'KES','play_event',pe.id,'Admin-qualified campaign play','POSTED','admin-play-credit:'||pe.id,now(),transfer,actor) on conflict(idempotency_key) do nothing;insert into public.notifications(recipient_profile_id,notification_type,title,body,metadata,link_url) values(participant_profile,'EARNINGS_CREDITED','Play approved','Your reviewed campaign play was approved and the earning entered its review period.',jsonb_build_object('play_id',pe.id,'amount',reward),case when part.participant_type='DJ' then '/dj/wallet' else '/matatu/wallet' end);end if;insert into public.audit_logs(actor_profile_id,action,entity_type,entity_id,previous_data,new_data,metadata) values(actor,'PLAY_'||p_outcome,'play_event',pe.id,jsonb_build_object('qualification_status',pe.qualification_status),jsonb_build_object('admin_outcome',p_outcome),jsonb_build_object('reason',p_reason,'note',p_note));end$$;

create function public.admin_update_payout(p_payout_id uuid,p_status public.payout_status,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare actor uuid;pr public.payout_requests;begin if not public.is_admin() then raise exception 'Admin access required';end if;select public.current_profile_id() into actor;select * into pr from public.payout_requests where id=p_payout_id for update;if pr.id is null or pr.status not in('REQUESTED','PROCESSING') then raise exception 'Payout is not actionable';end if;if p_status not in('PROCESSING','COMPLETED','FAILED','CANCELLED') then raise exception 'Invalid payout transition';end if;if p_status='COMPLETED' and pr.status<>'PROCESSING' then raise exception 'Payout must be processing before completion';end if;update public.payout_requests set status=p_status,processed_at=case when p_status in('COMPLETED','FAILED','CANCELLED') then now() else processed_at end,failure_reason=case when p_status='FAILED' then p_reason end,metadata=metadata||jsonb_build_object('development_mock',true,'updated_by',actor) where id=pr.id;insert into public.audit_logs(actor_profile_id,action,entity_type,entity_id,previous_data,new_data,metadata) values(actor,'PAYOUT_'||p_status,'payout_request',pr.id,jsonb_build_object('status',pr.status),jsonb_build_object('status',p_status),jsonb_build_object('reason',p_reason,'development_mock',true));insert into public.notifications(recipient_profile_id,notification_type,title,body,metadata,link_url) values(pr.requested_by,'PAYOUT_UPDATE','Payout status updated','Your payout request is now '||lower(p_status::text)||'.',jsonb_build_object('payout_id',pr.id,'status',p_status),case when exists(select 1 from public.profiles where id=pr.requested_by and role='DJ') then '/dj/wallet' else '/matatu/wallet' end);end$$;

create function public.admin_update_setting(p_key text,p_value jsonb,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare actor uuid;old jsonb;begin if not public.is_admin() then raise exception 'Admin access required';end if;if p_key not in('finance_policy','operations_policy') or jsonb_typeof(p_value)<>'object' or length(trim(p_reason))<3 then raise exception 'Invalid setting update';end if;if p_key='finance_policy' and ((p_value->>'platform_commission_bps')::integer not between 0 and 5000 or (p_value->>'minimum_payout')::numeric<0 or (p_value->>'settlement_review_hours')::integer not between 0 and 720) then raise exception 'Finance setting outside allowed range';end if;if p_key='operations_policy' and ((p_value->>'minimum_playback_percentage')::integer not between 1 and 100 or (p_value->>'daily_play_limit')::integer not between 1 and 1000) then raise exception 'Operations setting outside allowed range';end if;select public.current_profile_id() into actor;select value into old from public.business_settings where key=p_key for update;insert into public.business_setting_versions(setting_key,value,changed_by,reason) values(p_key,p_value,actor,p_reason);update public.business_settings set value=p_value,updated_at=now() where key=p_key;insert into public.audit_logs(actor_profile_id,action,entity_type,previous_data,new_data,metadata) values(actor,'SETTING_UPDATED','business_setting',old,p_value,jsonb_build_object('key',p_key,'reason',p_reason));end$$;

alter table public.admin_review_decisions enable row level security;alter table public.admin_notes enable row level security;alter table public.disputes enable row level security;alter table public.business_setting_versions enable row level security;
create policy admin_reviews_admin on public.admin_review_decisions for select to authenticated using(public.is_admin());create policy admin_notes_admin on public.admin_notes for select to authenticated using(public.is_admin());create policy disputes_admin on public.disputes for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy setting_versions_admin on public.business_setting_versions for select to authenticated using(public.is_admin());
grant select on public.admin_review_decisions,public.admin_notes,public.disputes,public.business_setting_versions to authenticated;grant insert,update on public.disputes to authenticated;grant execute on function public.admin_review_campaign(uuid,public.admin_review_outcome,text,text,text),public.admin_set_account_status(uuid,public.account_status,text,text),public.admin_set_verification(text,uuid,public.verification_status,text),public.admin_review_play(uuid,public.admin_review_outcome,text,text),public.admin_update_payout(uuid,public.payout_status,text),public.admin_update_setting(text,jsonb,text) to authenticated;

commit;
